version: '3'
services:
  mobilenet_v1:
    build:
      context: docker/test-tf-serving
      dockerfile: Dockerfile
    ports:
      - "9001:9000"
    environment:
      MODEL_URL: https://storage.googleapis.com/tf-models-839c7ddd-9cab-49fa-9b42-bde1a842086e/mobilenet_v1.tar.gz
  inception_v3:
    build:
      context: docker/test-tf-serving
      dockerfile: Dockerfile
    ports:
      - "9002:9000"
    environment:
      MODEL_URL: https://storage.googleapis.com/tf-models-839c7ddd-9cab-49fa-9b42-bde1a842086e/inception_v3.tar.gz
  xception:
    build:
      context: docker/test-tf-serving
      dockerfile: Dockerfile
    ports:
      - "9003:9000"
    environment:
      MODEL_URL: https://storage.googleapis.com/tf-models-839c7ddd-9cab-49fa-9b42-bde1a842086e/xception.tar.gz
